

services:
  # Master Nodes (Write-Enabled)
  redis-master1:
    image: redis:7.2-alpine
    container_name: redis-master1

    ports:
      - "7001:6379"
    volumes:
      - redis-master1-data:/data                # Named volume for persistence
      - ./conf/redis-node1.conf:/usr/local/etc/redis/redis-node1.conf
    networks:
      - etour-network
    command: redis-server /usr/local/etc/redis/redis-node1.conf
    environment:
      - REDIS_PASSWORD=Amaan@123
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis-master2:
    image: redis:7.2-alpine
    container_name: redis-master2

    ports:
      - "7002:6379"
    volumes:
      - redis-master2-data:/data
      - ./conf/redis-node1.conf:/usr/local/etc/redis/redis-node1.conf
    networks:
      - etour-network
    command: redis-server /usr/local/etc/redis/redis-node1.conf
    environment:
      - REDIS_PASSWORD=Amaan@123
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD} ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 3

  redis-master3:
    image: redis:7.2-alpine
    container_name: redis-master3

    ports:
      - "7003:6379"
    volumes:
      - redis-master3-data:/data
      - ./conf/redis-node1.conf:/usr/local/etc/redis/redis-node1.conf
    networks:
      - etour-network
    command: redis-server /usr/local/etc/redis/redis-node1.conf
    environment:
      - REDIS_PASSWORD=Amaan@123
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD} ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 3

  redis-master4:
    image: redis:7.2-alpine
    container_name: redis-master4

    ports:
      - "7004:6379"
    volumes:
      - redis-master4-data:/data
      - ./conf/redis-node1.conf:/usr/local/etc/redis/redis-node1.conf
    networks:
      - etour-network
    command: redis-server /usr/local/etc/redis/redis-node1.conf
    environment:
      - REDIS_PASSWORD=Amaan@123
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD} ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 3

  redis-master5:
    image: redis:7.2-alpine
    container_name: redis-master5

    ports:
      - "7005:6379"
    volumes:
      - redis-master5-data:/data
      - ./conf/redis-node1.conf:/usr/local/etc/redis/redis-node1.conf
    networks:
      - etour-network
    command: redis-server /usr/local/etc/redis/redis-node1.conf
    environment:
      - REDIS_PASSWORD=Amaan@123
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD} ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 3

  redis-master6:
    image: redis:7.2-alpine
    container_name: redis-master6

    ports:
      - "7006:6379"
    volumes:
      - redis-master6-data:/data
      - ./conf/redis-node1.conf:/usr/local/etc/redis/redis-node1.conf
    networks:
      - etour-network
    command: redis-server /usr/local/etc/redis/redis-node1.conf
    environment:
      - REDIS_PASSWORD=Amaan@123
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $${REDIS_PASSWORD} ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 3




  # Optional: Redis Exporter for Prometheus Monitoring
  # redis-exporter:
  #   image: oliver006/redis_exporter:latest
  #   ports:
  #     - "9121:
volumes:
  redis-master3-data:
  redis-master1-data:
  redis-master2-data:
  redis-master4-data:
  redis-master5-data:
  redis-master6-data:

networks:
  etour-network:
      external: true


#command to create cluster:podman exec -it redis-master1 redis-cli -a Amaan@123 --cluster create redis-master1:6379  redis-master2:6379  redis-master3:6379 redis-master4:6379 redis-master5:6379 redis-master6:6379 --cluster-replicas 1
