spring:
  application:
    name: ETour
  datasource:
    url: 'jdbc:postgresql://localhost:5432/keycloak'
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://etour.com/auth/realms/master'
    certs: 'http://etour.com/auth/realms/master/protocol/openid-connect/certs'
server:
  port: '1080'

redis:
  host: |
    ["redis://localhost:7000"]

