spring:
  application:
    name: ETour
  datasource:
    url: 'jdbc:postgresql://localhost:5432/etour_db'
    username: postgres
    password: Amaan@123
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost/auth/realms/etour'
    certs: 'http://localhost/auth/realms/etour/protocol/openid-connect/certs'
server:
  port: '1080'

redis:
  host: |
    ["redis://localhost:7000"]

