version: '3'
services:
  jenkins:
    container_name: jenkins-e
    build:
      context: .
      
      dockerfile: Dockerfile
    ports:
      - "8020:8080"
      - "50000:50000"  # Jenkins agent communication port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to run Docker commands
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped

volumes:
  jenkins_home:
